### ISSUE TITLE
Implement an Android App Generator

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-android#384]
* [x] App Generator Component 1: Create a Web Page with Form Elements to upload. [#382](https://github.com/fossasia/open-event-android/issues/382)
* [x] App Generator Component 2: Add Upload Functionality to Server of a zip of JSON files, schedule, speakers etc. Must be able to receive and store data entered by a user on the website [#434](https://github.com/fossasia/open-event-android/issues/434)
* [x] App Generator Component 3: Create a Script to generate an apk [#383] (https://github.com/fossasia/open-event-android/issues/383)
* [x] App Generator Component 4: Implement function to call or trigger the script to build and sign the apk after upload of JSON files (e.g. Trigger builds after adding json config file to the android repo) [#380](https://github.com/fossasia/open-event-android/issues/380) 
* [x] App Generator Component 5: Send event APK to user after build is finished #385 
* [x] App Generator Component 6: Allow user to download the entire Android app as an apk #390 
* [x] App Generator Component 7: Additionally offer option to call from a REST API URL later for hosted mode instead of uploading JSON files #382

**Comment by the-dagger** [comment]
@mariobehling Here are my plans regarding implementation of app-generator feature.
First we will try and get it to work on our server _without_ using Flask with some minor security loops. (I am allowing the web user to run the scripts as root)
After this is done, we will later move to Flask and deploy the app generator there.
Why flask?
Ease of implementation, and no security issues.
Also flask has easy maintenance which will benefit in the long run.

**Comment by mariobehling** [comment]
What about Nodejs?

**Comment by the-dagger** [comment]
@mariobehling Right now, I'm giving my final effort of trying to execute bash files from php.
If it works, well and good BUT if it doesn't then I'll use Node.js istead of PHP.
I'll have a look at the webapp's code to see how they are implementing these things using Node.

**Comment by mariobehling** [comment]
I think it would be very nice, if we could ultimately access the Android app builder through an API of the builder. So, it could potentially plugged into any system that offers a standardized API or JSON files in our format.

**Comment by the-dagger** [comment]
Yes, makes sense.
I'll have a look at that too once we get this to work.
Meanwhile I'll open an issue for this.

**Comment by mananwason** [comment]
@the-dagger @mariobehling only 2 pointers are left for now and we'll be doing this in the future, so moving this to a future milestone

**Comment by the-dagger** [comment]
Yep, got it :+1:

**Comment by the-dagger** [comment]
@mariobehling Can we close this as we have a separate issue that is open for API (#396)
Cheers.

**Comment by the-dagger** [comment]
Closing this as we have #396 for API calls to app generator
