### ISSUE TITLE
Make a folder with documentation about android app

### ISSUE THREAD

**Issue by mananwason** [fossasia/open-event-android#407]
As discussed with @mariobehling we need to create a folder and add documentation to setup ~~both~~ the android app ~~as well as the apk~~ generator.

As a start, please add all documentation in one folder in one file for the Android App `/docs/Android.md` and on file `/docs/AndroidGenerator.md`. 

Documentation needs the following:
* [x] Basic spec
* [x] How to set up the Android App Generator https://github.com/fossasia/open-event-android/issues/405
* [x] Put links in README pointing to relevant docs
* [x] How to build an Android app
* [x] How the Android app updates data
* [x] Wireframes
* [x] Screenshots
* [x] UI assets

**Comment by mariobehling** [comment]
@mananwason Let's not mix up things. Please focus on the Android app in the documentation. As discussed we can follow the documentation of [connfa](http://connfa.com/documentation/) in a lot of aspects.

**Comment by mananwason** [comment]
Okay @mariobehling I thought that we can add 2 different files in folder : One for the android app and other for the generator.

**Comment by mariobehling** [comment]
Yeah, probably better.
