### ISSUE TITLE
Alpha Launch Checklist

### ISSUE THREAD

**Issue by nikit19** [fossasia/open-event-android#506]
- [x] Merge development with Master

- [ ] Test `open-event-master-app-playStore-release-unsigned.apk` from the apk branch

- [ ] Upload the apk in console

**Comment by nikit19** [comment]
@iamareebjamal Since we are using the automatic signing the unsigned apk from the apk branch should be uploaded to the console right ?
How do I test the unsigned apk ? We can't install unsigned apps right ?

**Comment by nikit19** [comment]
@iamareebjamal Could you please select the option of re using the signing key in the console. I don't have the rights of doing that.
I'll do Build->Generate signed APK
After testing the APK I'll upload it right ? My keys would be replaced with the signing keys that are being reused in the console ?
Is it possible to add environment variables in the APK this way ?

**Comment by iamareebjamal** [comment]
Automatic signing of the app should be enabled in the repo. You should test the app thoroughly and then give me the app. I'll sign it with upload key and upload it on the console

**Comment by iamareebjamal** [comment]
Release apps can be made through terminal. Everything that gradle can do can be done through terminal. Orga App has been deployed for an year through terminal. But we'll need FOSSASIA's official STRIPE API key now @mariobehling

**Comment by nikit19** [comment]
@iamareebjamal I think we can launch the app without the key for now because STRIPE doesn't work on the server as far as I know. They are also using the test keys on the server.
Can we launch the app as a prototype for now. We have been asked to publish it in playstore for a long time, it would be nice if we are able to publish the app before the evaluations start

**Comment by iamareebjamal** [comment]
OK

**Comment by nikit19** [comment]
@iamareebjamal I have emailed you the apk. I have updated the Store listing in the console.
Please tell if something is wrong or if I have to add more details somewhere.

**Comment by iamareebjamal** [comment]
- [ ] The icon is not proper. Check the images I have shared and the ones in the app (My mistake as I forgot to convert text to path or tell you the font)
- [ ] The app theme does not match the icon.

You have 2 choices, either make these changes before launching the app for do it within the day of the launch and re-release with the automated deployment system

The deployment system must be added within 2 days as well

**Comment by simarsingh24** [comment]
I am creating the issues, we will fix those in a day lets launch the app for now

**Comment by nikit19** [comment]
@iamareebjamal Yeah let's launch the app. I already have sent the PR to automate the process https://github.com/fossasia/open-event-android/pull/278 so it should not take much time to re-release the app with the above suggested changes

**Comment by nikit19** [comment]
@iamareebjamal I didn't get the first point. Both the icons looks same to me. What changes needs to be done ?

**Comment by iamareebjamal** [comment]
See the e text font

**Comment by simarsingh24** [comment]
@iamareebjamal could you please tell us font or provide us the updated icon

**Comment by iamareebjamal** [comment]
Providing in a few minutes. BTW, I have published the app

**Comment by iamareebjamal** [comment]
[open-android.zip](https://github.com/fossasia/open-event-android/files/2276870/open-android.zip)

**Comment by iamareebjamal** [comment]
Ignore the previous ZIP

[open-android.zip](https://github.com/fossasia/open-event-android/files/2276902/open-android.zip)
