### ISSUE TITLE
Make single activity app with navigation architecture component

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-android#822]
To Make a single activity app - 
- [x] For navigation fragments and profile fragments as main activity host. PR #823 
- [x] For all root layout fragments. PR #831 
- [x] Remove search results activity. PR #839 
- [x] Handle authentication with main activity and remove authentication activity. PR #844 
- [x] Replace search time activity with fragment. PR #851 
- [ ] Replace search location activity with fragment.

**Would you like to work on the issue?**

- [x] Yes

**Comment by liveHarshit** [comment]
Please reopen. I mention it by mistake. One activity needs to remove.
